name: stepin_website
description: STEPIN Official Website 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6

  # Responsive
  flutter_screenutil: ^5.8.4
  responsive_builder: ^0.7.0

  # SEO
  seo_renderer: ^0.6.0

  # Localization
  easy_localization: ^3.0.2

  # Auto Route
  auto_route: ^7.7.1

  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/localization/
    - assets/images/

  fonts:
      - family: NotoSans
        fonts:
        - asset : assets/fonts/NotoSans/NotoSansKR-Light.otf
          weight: 300
        - asset : assets/fonts/NotoSans/NotoSansKR-Regular.otf
          weight: 400
        - asset : assets/fonts/NotoSans/NotoSansKR-Medium.otf
          weight: 600
        - asset : assets/fonts/NotoSans/NotoSansKR-Bold.otf
          weight: 800
