name: Dart Website

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dart Build & GA Add
    runs-on: ubuntu-latest
    steps:
    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_STORAGE }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Upload to Google Cloud Storage
      run: |-
        gsutil -m cp -r gs://stepin.ai/img.png .
        gsutil -m cp -r img.png gs://stepin.ai
        gsutil setmeta -r -h "Cache-Control: no-cache, no-store, max-age=0" gs://stepin.ai