name: Dart Website

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dart Build & GA Add
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Install Google Cloud SDK
      run: |
        curl https://sdk.cloud.google.com | bash
        exec -l $SHELL
        gcloud components install gsutil

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_STORAGE }}'
        
    - name: Upload to Google Cloud Storage
      run: |
        gsutil config
        gsutil ls