name: Dart Website

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dart Build & GA Add
    runs-on: ubuntu-latest
    permissions:
    steps:
    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        service_account_key: '${{ secrets.GOOGLE_CREDENTIALS_STORAGE }}'
        project_id: 'stepin-website'
        
    - name: Upload to Google Cloud Storage
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS_STORAGE }}'
        gsutil -m cp -r gs://stepin.ai/img.png .
        gsutil -m cp -r gs://stepin.ai/img.png .
        gsutil -m cp -r img.png gs://stepin.ai/
        gsutil -m cp -r img.png gs://stepin.ai/
        gsutil -m cp -r img.png gs://stepin.ai/
        gsutil -h "Cache-Control: public, max-age=604800" set -r gs://stepin.ai/img.png