name: Dart Website

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dart Build & GA Add
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Install Google Cloud SDK
      run: |
        curl https://sdk.cloud.google.com | bash
        exec -l $SHELL
        gcloud components install gsutil

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/240629120330/locations/global/workloadIdentityPools/gitihub-action'
        service_account: 'storage-creator@stepin-prod.iam.gserviceaccount.com'
        
    - name: Upload to Google Cloud Storage
      run: |
        gsutil ls